# Generated by Django 5.2.6 on 2025-10-03 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_category_options_post_view_alter_post_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='view',
        ),
    ]
