# Generated by Django 5.2.6 on 2025-10-06 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_post_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postviews',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='post_View', to='blog.post'),
        ),
    ]
